name: manually deploy to stage

on: [workflow_dispatch]

permissions: write-all

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hi there
        run: echo hi there $USER $TASK
      - name: env there
        run: env
  deploy:
    runs-on: ubuntu-latest
    env:
      USER: me
      TASK: say hellop
    needs: hello
    steps:
      - name: goodbye
        run: echo goodbye  $USER $TASK